baseURL = "http://wwq666.github.io/"
defaultContentLanguage = "zh-cn" 
languageCode = "zh-cn"
title = "wwq技术博客"
enableEmoji = true
enableRobotsTXT = true
theme = "jane"
paginate = 5 # 首页每页显示的文章数
hasCJKLanguage = true # 自动检测是否包含 中文\日文\韩文

[author]
  name = "wwq"

[sitemap]
  changefreq = "weekly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  since = "2019" # 站点建立时间
  homeFullContent = false # if false, show post summaries on home page. Othewise show full content.
  archive-paginate = 20 # 归档、标签、分类每页显示的文章数目
  dateFormatToUse = "2006-01-02"
  moreMeta = true  # 是否显示字数统计与阅读时间
  showMenuLanguageChooser = true
  showAuthorInfo = true # show author info below the article
  photoswipe = true # 是否启用图片可点击

  [params.utteranc]
    enable = true
    repo = "wwq666/wwq666.github.io"    # 存储评论的Repo，格式为 owner/repo
    issueTerm = "pathname"  #表示你选择以那种方式让github issue的评论和你的文章关联。
    theme = "github-light" # 样式主题，有github-light和github-dark两种
    label = "BlogComments"  # Github Issue的标签,要先在repo里面建立这个标签
  
  [params.reward]                                         # 文章打赏
    enable = false
    wechat = "/wechat.jpg"
    alipay = "/alipay.jpg" 
  
  [params.counter.busuanzi]  # a Chinese visitor counter  # 不蒜子计数器
    enable = true

  [params.social]                                         # 社交链接
    a-email = "mailto:your@email.com"
    b-github = "http://github.com/wwq666"
    c-weibo = "http://localhost:1313"
    d-zhihu = "http://localhost:1313"

[[menu.main]] # 配置目录
  name = "首页"
  weight = 1
  identifier = "home"
  url = "/"
[[menu.main]]
  name = "全部文章"
  weight = 2
  identifier = "archives"
  url = "/post/"
[[menu.main]]
  name = "标签"
  weight = 3
  identifier = "tags"
  url = "/tags/"
[[menu.main]]
  name = "关于"
  weight = 4
  identifier = "about"
  url = "/about/"
